CREATE TABLE mytable(
   id                       VARCHAR(22) NOT NULL PRIMARY KEY
  ,alias                    VARCHAR(48) NOT NULL
  ,name                     VARCHAR(32) NOT NULL
  ,image_url                VARCHAR(68) NOT NULL
  ,is_closed                VARCHAR(5) NOT NULL
  ,url                      VARCHAR(205) NOT NULL
  ,review_count             INTEGER  NOT NULL
  ,categories0alias         VARCHAR(16) NOT NULL
  ,categories0title         VARCHAR(25) NOT NULL
  ,categories1alias         VARCHAR(14)
  ,categories1title         VARCHAR(15)
  ,categories2alias         VARCHAR(16)
  ,categories2title         VARCHAR(18)
  ,rating                   NUMERIC(3,1) NOT NULL
  ,coordinateslatitude      NUMERIC(18,15) NOT NULL
  ,coordinateslongitude     NUMERIC(19,14) NOT NULL
  ,transactions0            VARCHAR(22)
  ,price                    VARCHAR(4) NOT NULL
  ,locationaddress1         VARCHAR(17) NOT NULL
  ,locationaddress2         VARCHAR(11)
  ,locationaddress3         VARCHAR(7)
  ,locationcity             VARCHAR(13) NOT NULL
  ,locationzip_code         INTEGER  NOT NULL
  ,locationcountry          VARCHAR(2) NOT NULL
  ,locationstate            VARCHAR(2) NOT NULL
  ,locationdisplay_address0 VARCHAR(17) NOT NULL
  ,locationdisplay_address1 VARCHAR(23) NOT NULL
  ,locationdisplay_address2 VARCHAR(23)
  ,phone                    INTEGER 
  ,display_phone            VARCHAR(14)
  ,distance                 NUMERIC(18,13) NOT NULL
  ,transactions1            VARCHAR(8)
  ,transactions2            VARCHAR(8)
);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('f-m7-hyFzkf0HSEeQ2s-9A','fog-harbor-fish-house-san-francisco-2','Fog Harbor Fish House','https://s3-media2.fl.yelpcdn.com/bphoto/by8Hh63BLPv_HUqRUdsp_w/o.jpg','false','https://www.yelp.com/biz/fog-harbor-fish-house-san-francisco-2?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',9175,'seafood','Seafood','wine_bars','Wine Bars','cocktailbars','Cocktail Bars',4.5,37.80898821475503,-122.41029651587517,'restaurant_reservation','$$','39 Pier','Ste a - 202',NULL,'San Francisco',94133,'US','CA','39 Pier','Ste a - 202','San Francisco, CA 94133',+14159692010,'(415) 969-2010',5820.143221179387,NULL,NULL);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('oT08T3Vpn1I7jDmrBBRMTw','house-of-prime-rib-san-francisco','House of Prime Rib','https://s3-media4.fl.yelpcdn.com/bphoto/HLrjaMoAgYSac0vx71YpCA/o.jpg','false','https://www.yelp.com/biz/house-of-prime-rib-san-francisco?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',8496,'tradamerican','American (Traditional)','steak','Steakhouses','wine_bars','Wine Bars',4,37.79338,-122.4225,NULL,'$$$','1906 Van Ness Ave',NULL,NULL,'San Francisco',94109,'US','CA','1906 Van Ness Ave','San Francisco, CA 94109',NULL,+14158854605,'(415) 885-4605',3827.4799374720046,NULL,NULL);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('n6L5VIGunR51-D55C-eYeQ','foreign-cinema-san-francisco','Foreign Cinema','https://s3-media3.fl.yelpcdn.com/bphoto/cw5y2LSOIE-EVNjKK_d7SQ/o.jpg','false','https://www.yelp.com/biz/foreign-cinema-san-francisco?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',5359,'breakfast_brunch','Breakfast & Brunch','mediterranean','Mediterranean','cocktailbars','Cocktail Bars',4,37.75637,-122.41925,'delivery','$$$','2534 Mission St',NULL,NULL,'San Francisco',94110,'US','CA','2534 Mission St','San Francisco, CA 94110',NULL,+14156487600,'(415) 648-7600',1595.992511967024,NULL,NULL);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('HHtpR0RslupSQ99GIIwW5A','marufuku-ramen-san-francisco-5','Marufuku Ramen','https://s3-media4.fl.yelpcdn.com/bphoto/ouK2VmW0SrI70jsJpTxJhw/o.jpg','false','https://www.yelp.com/biz/marufuku-ramen-san-francisco-5?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',4524,'ramen','Ramen',NULL,NULL,NULL,NULL,4.5,37.785014,-122.431842,'pickup','$$','1581 Webster St','Ste 235',NULL,'San Francisco',94115,'US','CA','1581 Webster St','Ste 235','San Francisco, CA 94115',+14158729786,'(415) 872-9786',2717.1759329403035,'delivery',NULL);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('lJAGnYzku5zSaLnQ_T6_GQ','brendas-french-soul-food-san-francisco-6','Brenda''s French Soul Food','https://s3-media2.fl.yelpcdn.com/bphoto/-bch1_Who1F28YFqlsiuWA/o.jpg','false','https://www.yelp.com/biz/brendas-french-soul-food-san-francisco-6?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',12000,'breakfast_brunch','Breakfast & Brunch','southern','Southern','cajun','Cajun/Creole',4,37.78291531984934,-122.41889950001861,'delivery','$$','652 Polk St',NULL,NULL,'San Francisco',94102,'US','CA','652 Polk St','San Francisco, CA 94102',NULL,+14153458100,'(415) 345-8100',2893.406621737596,NULL,NULL);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('KkAVX3Wb7E3lP5F_f_8pXg','liholiho-yacht-club-san-francisco-2','Liholiho Yacht Club','https://s3-media3.fl.yelpcdn.com/bphoto/fOYW8NHV-SDkRdclG4ueGA/o.jpg','false','https://www.yelp.com/biz/liholiho-yacht-club-san-francisco-2?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',2614,'bars','Bars','newamerican','American (New)','seafood','Seafood',4.5,37.78843914681705,-122.41450866001664,'delivery','$$$','871 Sutter St',NULL,NULL,'San Francisco',94109,'US','CA','871 Sutter St','San Francisco, CA 94109',NULL,NULL,NULL,3618.7710453076415,NULL,NULL);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('Xg-FyjVKAN70LO4u4Z1ozg','hog-island-oyster-san-francisco-2','Hog Island Oyster','https://s3-media4.fl.yelpcdn.com/bphoto/Kozd3NJMSaT6S3J2kYAc1g/o.jpg','false','https://www.yelp.com/biz/hog-island-oyster-san-francisco-2?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',6901,'seafood','Seafood','seafoodmarkets','Seafood Markets','raw_food','Live/Raw Food',4.5,37.795831,-122.393303,NULL,'$$','1 Ferry Bldg',NULL,'Shop 11','San Francisco',94111,'US','CA','1 Ferry Bldg','Shop 11','San Francisco, CA 94111',+14153917117,'(415) 391-7117',5428.15670676801,NULL,NULL);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('ttarnopezxmp2ROB1N2PaA','nopa-san-francisco','Nopa','https://s3-media4.fl.yelpcdn.com/bphoto/QOc_docjeCrDHlckTaDE2A/o.jpg','false','https://www.yelp.com/biz/nopa-san-francisco?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',5378,'newamerican','American (New)','desserts','Desserts','cocktailbars','Cocktail Bars',4,37.77483,-122.43746,'delivery','$$$','560 Divisadero St',NULL,NULL,'San Francisco',94117,'US','CA','560 Divisadero St','San Francisco, CA 94117',NULL,+14158648643,'(415) 864-8643',1559.1831881623302,NULL,NULL);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('i09UMzccKgyLwGYKDVP28w','surisan-san-francisco','Surisan','https://s3-media3.fl.yelpcdn.com/bphoto/TRmQFBMztDCAlp_ol7IMbA/o.jpg','false','https://www.yelp.com/biz/surisan-san-francisco?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',3199,'korean','Korean','newamerican','American (New)','breakfast_brunch','Breakfast & Brunch',4.5,37.80678,-122.41756,'restaurant_reservation','$$','505 Beach St',NULL,NULL,'San Francisco',94133,'US','CA','505 Beach St','San Francisco, CA 94133',NULL,+14157718449,'(415) 771-8449',5366.476620396218,'pickup','delivery');
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('Tttm1r5Dw1sRMCfc3EQWPw','boulevard-san-francisco','Boulevard','https://s3-media2.fl.yelpcdn.com/bphoto/JY3eemL-y4H4mD0iKihrew/o.jpg','false','https://www.yelp.com/biz/boulevard-san-francisco?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',2792,'newamerican','American (New)',NULL,NULL,NULL,NULL,4,37.79322,-122.39298,'delivery','$$$$','1 Mission St',NULL,NULL,'San Francisco',94105,'US','CA','1 Mission St','San Francisco, CA 94105',NULL,+14155436084,'(415) 543-6084',5245.033147608948,NULL,NULL);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('WavvLdfdP6g8aZTtbBQHTw','gary-danko-san-francisco','Gary Danko','https://s3-media3.fl.yelpcdn.com/bphoto/eyYUz3Xl7NtcJeN7x7SQwg/o.jpg','false','https://www.yelp.com/biz/gary-danko-san-francisco?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',5837,'newamerican','American (New)','french','French','wine_bars','Wine Bars',4.5,37.80587,-122.42058,NULL,'$$$$','800 N Point St',NULL,NULL,'San Francisco',94109,'US','CA','800 N Point St','San Francisco, CA 94109',NULL,+14157492060,'(415) 749-2060',5191.341803207417,NULL,NULL);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('mSMZJj2pFvttWLpcDmgrEA','tonys-pizza-napoletana-san-francisco','Tony''s Pizza Napoletana','https://s3-media1.fl.yelpcdn.com/bphoto/DvQZHMo2vHsASJKxCDwoZw/o.jpg','false','https://www.yelp.com/biz/tonys-pizza-napoletana-san-francisco?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',6388,'pizza','Pizza','italian','Italian','cocktailbars','Cocktail Bars',4,37.8003315377662,-122.409053979377,'pickup','$$','1570 Stockton St',NULL,NULL,'San Francisco',94133,'US','CA','1570 Stockton St','San Francisco, CA 94133',NULL,+14158359888,'(415) 835-9888',5002.084940639829,'delivery',NULL);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('CYttYTEiQuhSfo3SEh79fA','shizen-vegan-sushi-bar-and-izakaya-san-francisco','Shizen Vegan Sushi Bar & Izakaya','https://s3-media4.fl.yelpcdn.com/bphoto/-1BWnyjrsDmTmXH_3wZl_w/o.jpg','false','https://www.yelp.com/biz/shizen-vegan-sushi-bar-and-izakaya-san-francisco?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',2248,'sushi','Sushi Bars','vegan','Vegan','izakaya','Izakaya',4.5,37.7683096,-122.4216669,'restaurant_reservation','$$$','370 14th St',NULL,NULL,'San Francisco',94103,'US','CA','370 14th St','San Francisco, CA 94103',NULL,+14156785767,'(415) 678-5767',1541.4148356059607,NULL,NULL);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('wGl_DyNxSv8KUtYgiuLhmA','bi-rite-creamery-san-francisco','Bi-Rite Creamery','https://s3-media3.fl.yelpcdn.com/bphoto/ZFLw9lTtUH3R67b4pvb3tg/o.jpg','false','https://www.yelp.com/biz/bi-rite-creamery-san-francisco?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',10058,'icecream','Ice Cream & Frozen Yogurt',NULL,NULL,NULL,NULL,4.5,37.761591,-122.425717,'delivery','$$','3692 18th St',NULL,NULL,'San Francisco',94110,'US','CA','3692 18th St','San Francisco, CA 94110',NULL,+14156265600,'(415) 626-5600',946.3867385272524,NULL,NULL);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('8dUaybEPHsZMgr1iKgqgMQ','sotto-mare-san-francisco-4','Sotto Mare','https://s3-media3.fl.yelpcdn.com/bphoto/o3hIcGLMxV_5ynxEjGWGrw/o.jpg','false','https://www.yelp.com/biz/sotto-mare-san-francisco-4?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',4879,'seafood','Seafood','italian','Italian','bars','Bars',4.5,37.79979,-122.40834,'pickup','$$','552 Green St',NULL,NULL,'San Francisco',94133,'US','CA','552 Green St','San Francisco, CA 94133',NULL,+14153983181,'(415) 398-3181',4970.484877370465,'delivery',NULL);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('XQLmEdXoMzOpffwoFaBtaQ','kitchen-story-san-francisco','Kitchen Story','https://s3-media3.fl.yelpcdn.com/bphoto/NFhzbxcz4No5Ny8_IHdPMw/o.jpg','false','https://www.yelp.com/biz/kitchen-story-san-francisco?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',3954,'breakfast_brunch','Breakfast & Brunch','asianfusion','Asian Fusion','newamerican','American (New)',4,37.764290777795395,-122.43072410226956,'restaurant_reservation','$$','3499 16th St',NULL,NULL,'San Francisco',94114,'US','CA','3499 16th St','San Francisco, CA 94114',NULL,+14155254905,'(415) 525-4905',628.7327818809532,'pickup','delivery');
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('PsY5DMHxa5iNX_nX0T-qPA','kokkari-estiatorio-san-francisco','Kokkari Estiatorio','https://s3-media2.fl.yelpcdn.com/bphoto/FTQfPJubJEtYeyHqwAsVKw/o.jpg','false','https://www.yelp.com/biz/kokkari-estiatorio-san-francisco?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',5074,'greek','Greek','mediterranean','Mediterranean',NULL,NULL,4.5,37.796996,-122.399661,'pickup','$$$','200 Jackson St',NULL,NULL,'San Francisco',94111,'US','CA','200 Jackson St','San Francisco, CA 94111',NULL,+14159810983,'(415) 981-0983',5153.879756630951,'delivery',NULL);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('4KfQnlcSu4bbTqnvGdGptw','beretta-san-francisco','Beretta','https://s3-media2.fl.yelpcdn.com/bphoto/HKxMJ8q8fzOY76hy7ACIag/o.jpg','false','https://www.yelp.com/biz/beretta-san-francisco?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',4092,'italian','Italian','pizza','Pizza','breakfast_brunch','Breakfast & Brunch',4,37.7538556,-122.420628,'restaurant_reservation','$$','1199 Valencia St',NULL,NULL,'San Francisco',94110,'US','CA','1199 Valencia St','San Francisco, CA 94110',NULL,+14156951199,'(415) 695-1199',1596.0798340858553,'delivery',NULL);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('uBaXDGwJPUkOSLWxS2vZ9Q','lazy-bear-san-francisco-5','Lazy Bear','https://s3-media3.fl.yelpcdn.com/bphoto/I3yhxGxciarZn4J8QJWBkw/o.jpg','false','https://www.yelp.com/biz/lazy-bear-san-francisco-5?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',758,'newamerican','American (New)',NULL,NULL,NULL,NULL,4.5,37.76041,-122.41969,NULL,'$$$$','3416 19th St',NULL,NULL,'San Francisco',94110,'US','CA','3416 19th St','San Francisco, CA 94110',NULL,+14158749921,'(415) 874-9921',1471.9330512507197,NULL,NULL);
INSERT INTO mytable(id,alias,name,image_url,is_closed,url,review_count,categories0alias,categories0title,categories1alias,categories1title,categories2alias,categories2title,rating,coordinateslatitude,coordinateslongitude,transactions0,price,locationaddress1,locationaddress2,locationaddress3,locationcity,locationzip_code,locationcountry,locationstate,locationdisplay_address0,locationdisplay_address1,locationdisplay_address2,phone,display_phone,distance,transactions1,transactions2) VALUES ('ykvr3ib1gHQHI4tznSn8iA','wayfare-tavern-san-francisco-2','Wayfare Tavern','https://s3-media3.fl.yelpcdn.com/bphoto/PF0Gwry7SVfbI5tforgXgg/o.jpg','false','https://www.yelp.com/biz/wayfare-tavern-san-francisco-2?adjust_creative=UtBA8zcRRcAT3rccRlgubg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=UtBA8zcRRcAT3rccRlgubg',4383,'tradamerican','American (Traditional)',NULL,NULL,NULL,NULL,4,37.794169,-122.402359,'pickup','$$$','558 Sacramento St',NULL,NULL,'San Francisco',94111,'US','CA','558 Sacramento St','San Francisco, CA 94111',NULL,+14157729060,'(415) 772-9060',4760.381794639864,'delivery',NULL);
